### PR TITLE
Make flake8 usable

### PR DESCRIPTION
**Pull request by jodal**
This PR starts out by ignoring all current flake8 warnings, then continues to fix a set of warnings in each commit. The hope is to make this at all possible to review and merge.

In the end, only warnings about too long lines and comments not starting with "# " are ignored. Everything is free for all other flake8 warnings, making flake8 a very useful tool to catch bugs early.

### CODE REVIEW

**Comment by jodal** [comment]
The py36 build passed. Both py35 and py37 failed because of network connectivity with test.mosquitto.org. Someone with access to rerun the tests should do so later.

**Comment by jodal** [comment]
This might look like huge changes, but if reviewing commit-by-commit, it should hopefully prove digestible.

**Comment by njouanin** [comment]
This PR can't be merged unless CI tests succeed. Can you fix it ?

**Comment by jodal** [comment]
As mentioned in the first comment, the tests seems to have failed simply because of network connectivity issues with test.mosquitto.org:

```
hbmqtt.client.ConnectException: Multiple exceptions: [Errno 110] Connect call failed ('37.187.106.16', 8883), [Errno 101] Network is unreachable
```

If you go to https://travis-ci.org/beerfactory/hbmqtt/builds/261646158 and click "Restart build" in the upper left, the tests will hopefully pass without any code changes.

**Comment by jodal** [comment]
Due to no response here, I pushed an empty commit to trigger a new Travis CI build. As expected, all tests passed.

**Pull request merged**
