### PR TITLE
Install default yaml files in scripts directory

### PR DESCRIPTION
**Pull request by hexdump42**
I found that when installing the hbmqtt package using setup.py, the auto created scripts hbmqtt, hbmqtt_pub & hbmqtt_sub throw an error that the default yaml filesdo not exist in the scripts directory. This small change to the setup.py will copy default_broker.yaml & default_client.yaml to the python env scripts directory.

### CODE REVIEW

**Comment by hexdump42** [comment]
I assume the travis ci is failing because it is building off master and my pull request was done against develop branch. e.g. scripts directory exists in develop branch but not master

**Comment by njouanin** [comment]
travis fails with this error:
error: can't copy 'scripts/default_broker.yaml': doesn't exist or not a regular file
I guess there's an error due to your PR when installing hbmqtt.

**Comment by hexdump42** [comment]
Travis first builds a source distribution from the git checkout using python setup.py sdist and then installs the sdist to create the wheel. Turns out the data_files directive doesn't include the yaml files as part of an sdist archive. Modified setup.py to use include_pacakage_data instead and added a MANIFEST.in file and now build & tests working.

**Comment by hexdump42** [comment]
I am new at using pull requests in github. Should this one be closed and another created since it's a later commit that fixes the issue?

https://github.com/hexdump42/hbmqtt/commit/71f0c29b492a52d8c51c9ca7bbbb3d34dd9c1da0

**Comment by njouanin** [comment]
Thanks for you contribution.

**Pull request merged**
