### PR TITLE
Move scripts module into hbmqtt module

### LINKED ISSUE #166: Package installs too generically named "scripts" module
Background:

- PR #131: Don't install example scripts
- Issue #143: 0.9.3 broken: scripts folder not found
- Commit 530eedba278a2cebf34cc10d9472670dc03689de: Restore __init__ file because these scripts are not examples scripts

I see from #143 that the scripts module is in fact used, thus my suggestions from #131 does not apply. However, the original issue still stands:

hbmqtt occupies the very generic Python module name `scripts` on all systems it is installed on.

I suggest to move the `scripts` module to for example `hbmqtt.scripts`.

### PR DESCRIPTION
**Pull request by jodal**
Fixes #166

### CODE REVIEW

**Comment by jodal** [comment]
I've updated this PR with the patch that is part of the hbmqtt 0.9.5-1 Debian package.

**Comment by jodal** [comment]
Is there any hope of getting this merged? Anything you'd like to see changed?

I'd very much like to drop the custom patch from the Debian package.

**Comment by jodal** [comment]
I've now rebased this pull request on top of the current master to make it easy to merge.

**Comment by jodal** [comment]
I'm cleaning up my list of open PRs. This PR has been open for almost 3 years and it's almost 2 years since the last commit to this repo, so I'm not spending any more effort here.

**Comment by FlorianLudwig** [comment]
@jodal btw we have your change over in the fork amqtt: https://github.com/Yakifo/amqtt/tree/master/amqtt/scripts

**Pull request closed without merging**
